// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'colorDot': string;
  'container': string;
  'inline': string;
  'white': string;
}
declare var cssExports: CssExports;
export = cssExports;
