// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'headline': string;
  'score': string;
}
declare var cssExports: CssExports;
export = cssExports;
