// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'blurred': string;
  'board': string;
  'game': string;
  'hint': string;
  'originallyBlack': string;
  'originallyWhite': string;
  'player1': string;
  'player2': string;
  'white': string;
}
declare var cssExports: CssExports;
export = cssExports;
